services:
  minishop-db:
    image: mysql:8.0
    container_name: minishop-db
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - monitoring
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MYSQL_USER}", "--password=${MYSQL_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2GB

  app:
    build: .
    container_name: minishop-app
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: "-Xms256m -Xmx512m"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1GB
        reservations:
          cpus: '0.5'
          memory: 512MB
    depends_on:
      minishop-db:
        condition: service_healthy
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512MB

  grafana:
    image: grafana/grafana
    container_name: grafana
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512MB

volumes:
  mysql_data:
  grafana_data:

networks:
  monitoring:
    driver: bridge